name: read file manually
on : 
    workflow_dispatch:

jobs:
    read-file:
      runs-on: ubuntu-22.04

      steps:
         - name: Check repository
           uses: actions/checkout@v4

         - name: Read app.txt
           run: cat app.txt
           
